######################################

# This script defines the project pipeline - it specifys the execution orders for all the code in this
# repo using a series of actions.

######################################

version: '3.0'

expectations:
  population_size: 100000

actions:
  
  # Extract data ----
  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-dir=output/data
    outputs:
      highly_sensitive:
        cohort: output/data/input.csv
        
  # Process data ----
  data_process:
    run: r:latest analysis/data_process.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data1: output/data/data_all.rds
        data2: output/data/data_processed.rds
        
  # Inclusion/exclusion flow chart ----
  flow_chart:
    run: r:latest analysis/flow_chart.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        data: output/data/flowchart.csv

  # Data properties ----      
  data_properties:
    run: r:latest analysis/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        cohort: output/data_properties/data_processed*.txt

  # Data summaries ----
  simple_summaries:
    run: r:latest -e 'rmarkdown::render("analysis/simple_summaries.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output/markdown")'
    needs: [generate_study_population, data_process]
    outputs:
      moderately_sensitive:
        html: output/markdown/simple_summaries.html
  
  # Table 1 ----
  table_1:
    run: r:latest analysis/table_1.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        table: output/tables/table1*.html
  
  # Table 2 ----
  table_2:
    run: r:latest analysis/table_2.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        table1: output/tables/table2.html
        table2: output/tables/table2_redacted.html
  
  table_ckd:
    run: r:latest analysis/table_ckd.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        table1: output/tables/table_ckd.html
        table2: output/tables/table_ckd_redacted.html
        table3: output/tables/table2_ckd.html
        table4: output/tables/table2_ckd_redacted.html

        
  # Figure 1 ----
  cummulative_incidence:
    run: r:latest analysis/cumulative_incidence.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        data: output/data/surv_data*.csv
        
  # Figure 2 ----
  figure_2:
    run: r:latest analysis/figure_2.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        png: output/figures/figure2*.png
        
        
        
        