---
title: "Censoring"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning= FALSE, message= FALSE}
# Preliminaries ----

## Import libraries
library(tidyverse)
library(lubridate)

## Output processed data to rds
dir.create(here::here("output", "markdown"), showWarnings = FALSE, recursive=TRUE)


## Custom function
tte <- function(origin_date, event_date, censor_date, na.censor=FALSE){
  # returns time-to-event date or time to censor date, which is earlier
  
  if (na.censor)
    time <- event_date-origin_date
  else
    time <- pmin(event_date-origin_date, censor_date-origin_date, na.rm=TRUE)
  as.numeric(time)
}

## Import data
data_extract0 <- read_csv(
  here::here("output", "data", "input.csv"),
  col_types = cols_only(
    
    patient_id = col_integer(),
    covid_hospital_admission_date = col_date(format="%Y-%m-%d"),
    covid_death = col_logical(),
    dereg_date = col_date(format="%Y-%m-%d"),
    death_date = col_date(format="%Y-%m-%d"),
    covid_death_date = col_date(format="%Y-%m-%d"),
    age = col_integer(),
    covid_vax_2_date = col_date(format="%Y-%m-%d"),
    covid_vax_1_date = col_date(format="%Y-%m-%d"),
    first_positive_test_date = col_date(format="%Y-%m-%d"),
    latest_positive_test_date = col_date(format="%Y-%m-%d")

    )) %>%
  mutate(
    
    # Positive test
    covid_positive_post_2vacc = ifelse(latest_positive_test_date > (covid_vax_2_date + 14), 1, 0),
    covid_positive_post_2vacc = ifelse(is.na(covid_positive_post_2vacc), 0, covid_positive_post_2vacc),
    
    # End date
    end_date = as.Date("2021-05-31", format = "%Y-%m-%d"),
    
    # Censoring
    censor_date = pmin(death_date, 
                       dereg_date, 
                       end_date, 
                       na.rm=TRUE),
    
    # Time since first dose
    follow_up_time_vax1 = tte(covid_vax_1_date,
                              end_date,
                              censor_date),
    
    # Time since second dose
    follow_up_time_vax2 = tte(covid_vax_2_date,
                              end_date,
                              censor_date),
    
    # Time to positive test
    time_to_positive_test = tte(covid_vax_2_date + 14,
                                latest_positive_test_date,
                                censor_date),
    time_to_positive_test = ifelse(covid_positive_post_2vacc == 1, time_to_positive_test, follow_up_time_vax2),
    time_to_positive_test = ifelse(is.na(covid_positive_post_2vacc), follow_up_time_vax2, time_to_positive_test),
    
    # Time to hospitalisation
    time_to_hospitalisation = tte(covid_vax_2_date + 14,
                                  covid_hospital_admission_date,
                                  censor_date),
    
    # Time to hospitalisation critical care
    time_to_itu = tte(covid_vax_2_date + 14,
                      covid_hospital_admission_date,
                      censor_date),
    
    # Time to covid death
    time_to_covid_death = tte(covid_vax_2_date + 14,
                              covid_death_date,
                              censor_date)
  )
```


## Dates coverage
```{r, echo = FALSE}
summary(data_extract0 %>% select(-patient_id))
```

## Positive tests
```{r, echo = FALSE}
dim(subset(data_extract0, !is.na(first_positive_test_date)))
dim(subset(data_extract0, !is.na(latest_positive_test_date)))

data_extract0 %>% 
  select(first_positive_test_date, latest_positive_test_date) %>%
  filter(first_positive_test_date == latest_positive_test_date) %>%
  dim()

data_extract0 %>% 
  select(first_positive_test_date, latest_positive_test_date) %>%
  filter(first_positive_test_date != latest_positive_test_date) %>%
  dim()

data_extract0 %>% 
  select(first_positive_test_date, latest_positive_test_date) %>%
  mutate(days_between = as.numeric(latest_positive_test_date - first_positive_test_date)) %>%
  ggplot(aes(x = days_between)) +
  geom_histogram(binwidth = 10)
  
```

## Age and follow-up
```{r, echo = FALSE}
ggplot(data_extract0, aes(x = age)) +
  geom_histogram(binwidth = 5) +
  theme_bw() 

ggplot(data_extract0, aes(x = age, y = follow_up_time_vax1)) +
  geom_point() +
  theme_bw() 

ggplot(data_extract0, aes(x = age, y = follow_up_time_vax2)) +
  geom_point() +
  theme_bw() 
```

## Ethnicity check
```{r, echo = FALSE}
ethnicity <- read_rds(here::here("output", "data", "data_all.rds"))

table(ethnicity$ethnicity)


```
